### ISSUE TITLE
Release Airbrake 1.1.4

### ISSUE THREAD

**Issue by pfhayes** [airbrake/airbrake-python#22]
Can we get a release of 1.1.4 so the python 3 compatibility is live?

**Comment by samstav** [comment]
Looks like it's here: https://pypi.python.org/pypi/airbrake/1.1.4, uploaded on 2015-01-30.

I'd forgotten to post the [release on GitHub](https://github.com/airbrake/airbrake-python/releases), sorry for the confusion. Here it is now:

https://github.com/airbrake/airbrake-python/releases/tag/v1.1.4

Note that [v1.1.4 on PyPI](https://pypi.python.org/pypi/airbrake/1.1.4) does not include this commit: https://github.com/airbrake/airbrake-python/commit/0fdadcd9b4700613ee1a10db3c78e16b82665bd1

We can cut a release (v1.1.5) to include that change if necessary.

**Comment by pfhayes** [comment]
Thanks! I'll let you decide if 1.1.5 needs to be cut (I don't know the nature of that change)
