### ISSUE TITLE
describeexctipn for airbrake?

### ISSUE THREAD

**Issue by mgracer48** [airbrake/airbrake-python#24]
How would i add airbrake code with logger
i already added this
```
import airbrake
logger = airbrake.getLogger(api_key=myapikeyishiddenforprivacy:), project_id=234209)
now i at the end of my game starter i have this
autoRun = ConfigVariableBool('toontown-auto-run', 1)
if autoRun:
    try:
        base.run()
    except SystemExit:
        raise
    except:
        print describeException()
        raise
```        
now how would i add logger.exception properly after describeexception so i report crashes to airbrake every time a person who plays my game crashes :)

**Comment by mgracer48** [comment]
basically i want to airbrake to do what describeexceiption does (no printing though) but adds it into my airbrake logs

**Comment by phumpal** [comment]
Why not replace `print describeException()` with something like

    logger.exception("He promised to leave toon town to us toons", extra=toontown_json)

Similar to [this](https://github.com/airbrake/airbrake-python#giving-your-exceptions-more-context) or [this](https://github.com/airbrake/airbrake-python/blob/master/tests/real_test.py#L26).

**Comment by phumpal** [comment]
@mgracer48 - were you able to get this resolved? can we close this out?

**Comment by phumpal** [comment]
@mgracer48 - closing this out as there's been no response. Feel free to reopen if you are still having issues.
