### ISSUE TITLE
Latest version (1.3.1) not in pypi

### ISSUE THREAD

**Issue by argos83** [airbrake/airbrake-python#28]
Latest version has not been published in Pypi. `pip install -U airbrake` still gets 1.2.1

**Comment by samstav** [comment]
@argos83 , thanks for calling this out. [Pushed 1.3.1 to PyPI](https://pypi.python.org/pypi/airbrake/1.3.1).

https://github.com/airbrake/airbrake-python/releases/tag/v1.3.1
