### ISSUE TITLE
Merge airbrake-django with airbrake-python

### ISSUE THREAD

**Issue by kyrylo** [airbrake/airbrake-python#30]
It's possible to merge https://github.com/airbrake/airbrake-django with this repo. I think this is the right thing to do.

**Comment by yorinasub17** [comment]
I'd like to help here. Any ideas/requests on how the merge should happen?

**Comment by samstav** [comment]
I haven't looked at airbrake-django, but intuitively it sounds like airbrake-python could just become a dependency. If physically merging them is the answer, does the description become: "airbrake-python has first-class support for django, ____, ___, etc." ? Where, in theory, support for other frameworks could get built-in over time? 

Other strategies to consider are building out support for plugins or hooks into airbrake-python to be leveraged by airbrake-django and others.

**Comment by kyrylo** [comment]
> @samstav 
> I haven't looked at airbrake-django, but intuitively it sounds like airbrake-python could just become a dependency

This is also an option. Ideally, it would be nice to do what we did with our Ruby notifier. We have https://github.com/airbrake/airbrake-ruby, which is similar to airbrake-python. We also have https://github.com/airbrake/airbrake, which depends on airbrake-ruby. airbrake/airbrake is basically a collection of various integrations with Ruby libraries, frameworks, etc. If it's possible to do the same thing with airbrake-python, this would be my most favourite option.

> @samstav 
> If physically merging them is the answer, does the description become: "airbrake-python has first-class support for django, ____, ___, etc." ? Where, in theory, support for other frameworks could get built-in over time?

If we decide to go this way, we would probably have to include everything in this repo as well. However as practice showed there won't be a lot of integrations. Django is one, what else? Tornado?

> @samstav 
> Other strategies to consider are building out support for plugins or hooks into airbrake-python to be leveraged by airbrake-django and others.

Sounds like a lot of work. Will we really have tons of integrations to justify this way?

**Comment by kyrylo** [comment]
@samstav do you have any experience with Django?

**Comment by samstav** [comment]
@kyrylo I don't...

but I agree with you here:

> If it's possible to do the same thing with airbrake-python, this would be my most favourite option.

**Comment by gregorynicholas** [comment]
please keep them separate .  leave a framework agnostic python package separate. let django do its own thing, there are lots of python projects that dont touch django .

**Comment by kyrylo** [comment]
@gregorynicholas this is the most preferred solution (section 1) https://github.com/airbrake/airbrake-python/issues/30#issuecomment-220305390

**Comment by phumpal** [comment]
To no one's fault this issue has sat w/out activity for quite some time.

FWIW Python 3.4+ support has been migrated to our new Python notifier [pybrake](https://github.com/airbrake/pybrake).

Support for Python 2.7 can still be found here in [airbrake-python](https://github.com/airbrake/airbrake-python) and the [airbrake-python-integrations](https://github.com/airbrake/airbrake-python-integrations) library which includes support Django.

If you're using [airbrake-django](https://github.com/airbrake/airbrake-django) and still on Python 2.7 please let us know and we will do our best to try an accommodate your use case.
