### ISSUE TITLE
Add user data if it's available

### ISSUE THREAD

**Issue by zachgoldstein** [airbrake/airbrake-python#34]
It would be great to add user support and remove this todo:
https://github.com/airbrake/airbrake-python/blob/master/airbrake/notifier.py#L99
```
# TODO(samstav)
#   add user info:
#       userID, userName, userEmail
#   add application info:
#       version, url, rootDirectory
```

**Comment by zachgoldstein** [comment]
Closing, this is included in https://github.com/airbrake/airbrake-python/issues/34

**Comment by kyrylo** [comment]
#34 is this issue.
