### ISSUE TITLE
Asyncio support?

### ISSUE THREAD

**Issue by hzlmn** [airbrake/airbrake-python#94]
Hi thanks for good tool and battery!

Asyncio/aiohttp stack is rapidly growing in usage and it will be really nice if library add support for async transport.

If you consider it as an addition i can create PR.

**Comment by phumpal** [comment]
@hzlmn good idea. Can we maintain backwards compatibility for Python 2.7? It appears the latest releases for asyncio/aiohttp only support Python 3.3 which was deprecated in #91.

Have you seen our "new" Python notifier https://github.com/airbrake/pybrake? It supports Python 3.4+

**Comment by hzlmn** [comment]
@phumpal Nope, only python 3.3 and later. Yep i found new version after i created an issue. `pybrake` has some async support as i can see, but it uses ThreadPool approach so maybe it would be good addition to provide "native" asyncio support and move this issue there.

**Comment by phumpal** [comment]
@hzlmn perfect, that sounds great. Thanks! Let's close this issue for now.

Heads up @vmihailenco and @anmic
